venues = [
    {
        "name": "Scope Arena",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 10000,
        "estimated_cost": 5000,
        "cost": 5000,
        "price_tier": "premium",
        "indoor_outdoor": "indoor",
        "venue_type": "arena",
        "type": "Arena",
        "style": "modern",
        "parking": True,
        "accessibility": True,
        "rating": 4.6,
        "phone": "(757) 000-1000",
        "website": "https://example.com/scope-arena",
        "description": "Large multi-purpose indoor venue for concerts, conferences, and major events."
    },
    {
        "name": "Chrysler Hall",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 2500,
        "estimated_cost": 2500,
        "cost": 2500,
        "price_tier": "premium",
        "indoor_outdoor": "indoor",
        "venue_type": "theater",
        "type": "Performing Arts",
        "style": "elegant",
        "parking": True,
        "accessibility": True,
        "rating": 4.7,
        "phone": "(757) 000-1100",
        "website": "https://example.com/chrysler-hall",
        "description": "Elegant performing arts venue suited for ceremonies, showcases, and upscale events."
    },
    {
        "name": "NorVa Theatre",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 1500,
        "estimated_cost": 1800,
        "cost": 1800,
        "price_tier": "mid",
        "indoor_outdoor": "indoor",
        "venue_type": "music venue",
        "type": "Music Venue",
        "style": "modern",
        "parking": True,
        "accessibility": True,
        "rating": 4.5,
        "phone": "(757) 000-1200",
        "website": "https://example.com/norva",
        "description": "Historic music venue with an energetic atmosphere and flexible event setup."
    },
    {
        "name": "Harrison Opera House",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 1632,
        "estimated_cost": 2000,
        "cost": 2000,
        "price_tier": "premium",
        "indoor_outdoor": "indoor",
        "venue_type": "opera house",
        "type": "Opera House",
        "style": "formal",
        "parking": True,
        "accessibility": True,
        "rating": 4.8,
        "phone": "(757) 000-1300",
        "website": "https://example.com/harrison-opera-house",
        "description": "Elegant historic venue that works well for galas, concerts, and formal programs."
    },
    {
        "name": "Attucks Theatre",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 625,
        "estimated_cost": 800,
        "cost": 800,
        "price_tier": "budget",
        "indoor_outdoor": "indoor",
        "venue_type": "historic theater",
        "type": "Historic Theatre",
        "style": "historic",
        "parking": True,
        "accessibility": True,
        "rating": 4.4,
        "phone": "(757) 000-1400",
        "website": "https://example.com/attucks-theatre",
        "description": "Historic cultural venue with a smaller footprint for intimate community events."
    },
    {
        "name": "Waterside District",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 1200,
        "estimated_cost": 1500,
        "cost": 1500,
        "price_tier": "mid",
        "indoor_outdoor": "mixed",
        "venue_type": "waterfront complex",
        "type": "Entertainment District",
        "style": "modern",
        "parking": True,
        "accessibility": True,
        "rating": 4.5,
        "phone": "(757) 000-1500",
        "website": "https://example.com/waterside-district",
        "description": "Waterfront complex with flexible spaces for celebrations, mixers, and entertainment-driven events."
    },
    {
        "name": "Town Point Park Pavilion",
        "city": "Norfolk",
        "location": "Norfolk",
        "capacity": 400,
        "estimated_cost": 900,
        "cost": 900,
        "price_tier": "budget",
        "indoor_outdoor": "outdoor",
        "venue_type": "park pavilion",
        "type": "Park Pavilion",
        "style": "casual",
        "parking": True,
        "accessibility": True,
        "rating": 4.3,
        "phone": "(757) 000-1600",
        "website": "https://example.com/town-point-park",
        "description": "Casual outdoor waterfront venue that works well for festivals, reunions, and relaxed gatherings."
    },
    {
        "name": "Harbor View Ballroom",
        "city": "Portsmouth",
        "location": "Portsmouth",
        "capacity": 300,
        "estimated_cost": 2200,
        "cost": 2200,
        "price_tier": "premium",
        "indoor_outdoor": "indoor",
        "venue_type": "ballroom",
        "type": "Ballroom",
        "style": "upscale",
        "parking": True,
        "accessibility": True,
        "rating": 4.7,
        "phone": "(757) 000-1700",
        "website": "https://example.com/harbor-view-ballroom",
        "description": "Upscale ballroom venue for banquets, receptions, and polished corporate events."
    }
]


catering = [
    {
        "name": "Campus Catering",
        "city": "Norfolk",
        "cuisine": "american",
        "service_type": "buffet",
        "type": "Buffet",
        "price_tier": "budget",
        "cost_per_person": 12,
        "dietary_options": ["vegetarian"],
        "rating": 4.1,
        "phone": "(757) 000-2000",
        "website": "https://example.com/campus-catering",
        "description": "Affordable buffet catering for campus and community events."
    },
    {
        "name": "Pizza Party Co.",
        "city": "Norfolk",
        "cuisine": "pizza",
        "service_type": "drop-off",
        "type": "Pizza",
        "price_tier": "budget",
        "cost_per_person": 8,
        "dietary_options": ["vegetarian"],
        "rating": 4.0,
        "phone": "(757) 000-2100",
        "website": "https://example.com/pizza-party",
        "description": "Simple, budget-friendly catering for casual student and office events."
    },
    {
        "name": "Gourmet Bites",
        "city": "Norfolk",
        "cuisine": "new american",
        "service_type": "plated",
        "type": "Premium",
        "price_tier": "premium",
        "cost_per_person": 20,
        "dietary_options": ["vegetarian", "gluten-free"],
        "rating": 4.8,
        "phone": "(757) 000-2200",
        "website": "https://example.com/gourmet-bites",
        "description": "Upscale plated catering with polished presentation for formal events."
    },
    {
        "name": "Snack Shack",
        "city": "Norfolk",
        "cuisine": "snacks",
        "service_type": "drop-off",
        "type": "Snacks",
        "price_tier": "budget",
        "cost_per_person": 5,
        "dietary_options": [],
        "rating": 3.9,
        "phone": "(757) 000-2300",
        "website": "https://example.com/snack-shack",
        "description": "Simple snack trays and light refreshment service for small informal events."
    },
    {
        "name": "Food Truck Collective",
        "city": "Norfolk",
        "cuisine": "mixed",
        "service_type": "food truck",
        "type": "Mixed",
        "price_tier": "mid",
        "cost_per_person": 15,
        "dietary_options": ["vegetarian"],
        "rating": 4.4,
        "phone": "(757) 000-2400",
        "website": "https://example.com/food-truck-collective",
        "description": "Flexible food truck catering with multiple cuisine options and casual energy."
    },
    {
        "name": "Bella Festa Catering",
        "city": "Norfolk",
        "cuisine": "italian",
        "service_type": "buffet",
        "type": "Italian",
        "price_tier": "mid",
        "cost_per_person": 18,
        "dietary_options": ["vegetarian"],
        "rating": 4.6,
        "phone": "(757) 000-2500",
        "website": "https://example.com/bella-festa",
        "description": "Italian buffet catering ideal for parties, banquets, and family-style service."
    },
    {
        "name": "Smoke & Spice BBQ",
        "city": "Virginia Beach",
        "cuisine": "bbq",
        "service_type": "buffet",
        "type": "BBQ",
        "price_tier": "mid",
        "cost_per_person": 16,
        "dietary_options": ["gluten-free"],
        "rating": 4.5,
        "phone": "(757) 000-2600",
        "website": "https://example.com/smoke-and-spice",
        "description": "Hearty BBQ buffet service that works well for outdoor and casual gatherings."
    }
]
